CREATE TABLE IF NOT EXISTS offsets (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  offset INT 
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS event (
  offset INT UNSIGNED NOT NULL PRIMARY KEY,
  value BLOB 
) engine=InnoDB;
